name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  # pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: kim0
          password: ${{ secrets.HVNTOKEN }}

      # - name: Login to Github Packages
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GHCRRWTOKEN }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.platform }}
          # relative path to the place where source code with Dockerfile is located
          # context: ./src/samples/simple
          # Note: tags has to be all lower-case
          tags: |
            docker.io/kim0/gh-actions:${{ matrix.platform }}-latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}